server:
  port: 7001

eureka:
  instance:
    hostname: localhost
  client:
    # 是否需要向 eureka 服务端注册自身信息（以成为 eureka 客户端）。这里设置为 false，因为这里是 eureka 的服务端
    register-with-eureka: false
    # 是否需要向 eureka 服务端获取抓取 eureka 客户端信息。这里设置为 false
    fetch-registry: false
    # eureka 服务端交互地址（eureka 客户端服务注册方调用这个地址进行交互），默认为 http://localhost:8761/eureka/
    # key 为 defaultZone，value 为 交互地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
